### ISSUE TITLE
Server starts but has error (using mysql)

### ISSUE THREAD

**Issue by LadyMartel** [go-bootstrap/go-bootstrap#49]
I'm new to go so maybe there's something obvious here that I'm missing. The core version without a db worked as expected. I tried  However, when I try to access localhost:8888 for a project that uses a mysql db, the output looks like the following. I'm on a macOS Sierra.

```
INFO[0000] Running HTTP server on :8888    
2017/01/01 13:07:17 http: panic serving [::1]:50562: interface conversion: interface is nil, not sessions.Store
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc42019e000)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x47c1c0, 0xc42018e3c0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/username/mysqldbtest/handlers.GetHome(0x707220, 0xc4201980d0, 0xc4201ac2d0)
	/Users/Me/Documents/Programming/work/src/github.com/username/mysqldbtest/handlers/home.go:15 +0x13d
net/http.HandlerFunc.ServeHTTP(0x534ed0, 0x707220, 0xc4201980d0, 0xc4201ac2d0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42006fdb0, 0x707220, 0xc4201980d0, 0xc4201ac2d0)
	/Users/Me/Documents/Programming/work/src/github.com/gorilla/mux/mux.go:114 +0x10d
github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x707220, 0xc4201980d0, 0xc4201ac000)
	/Users/Me/Documents/Programming/work/src/github.com/carbocation/interpose/interpose.go:55 +0x63
net/http.HandlerFunc.ServeHTTP(0xc4201962a0, 0x707220, 0xc4201980d0, 0xc4201ac000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/username/mysqldbtest/middlewares.SetSessionStore.func1.1(0x707220, 0xc4201980d0, 0xc4201ac000)
	/Users/Me/Documents/Programming/work/src/github.com/username/mysqldbtest/middlewares/middlewares.go:27 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc4201962d0, 0x707220, 0xc4201980d0, 0xc4201ac000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/username/mysqldbtest/middlewares.SetDB.func1.1(0x707220, 0xc4201980d0, 0xc4201ac000)
	/Users/Me/Documents/Programming/work/src/github.com/username/mysqldbtest/middlewares/middlewares.go:17 +0xde
net/http.HandlerFunc.ServeHTTP(0xc420190140, 0x707220, 0xc4201980d0, 0xc4201ac000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc4200db860, 0x707220, 0xc4201980d0, 0xc4201ac000)
	/Users/Me/Documents/Programming/work/src/github.com/carbocation/interpose/interpose.go:85 +0x67
net/http.serverHandler.ServeHTTP(0xc4200a0980, 0x707220, 0xc4201980d0, 0xc4201ac000)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42019e000, 0x7079e0, 0xc42018e180)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

```

I generated the project using this:
```
 $GOPATH/bin/go-bootstrap -dir github.com/username/mysqldbtest -template mysql
```
The output seemed to indicate the setup was successful. Any thoughts?

**Comment by glow-mdsol** [comment]
So, this is down to the issue with the switching of context provider in later versions of go (go > 1.7).  To fix this make the changes recommended in https://github.com/mikeflynn/go-alexa/pull/8/commits/a4eb41d83784e33b9ae4b524ff11971eb75c34d6 and it should work

To modify the `context.Get` calls change from:
```golang
sessionStore := context.Get(req, "sessionStore").(sessions.Store)
```
to
```golang
sessionStore := req.Context().Value( "sessionStore").(sessions.Store)
```

and the `context.Set` calls from:
```golang
context.Set(req, "sessionStore", sessionStore)
```
to
```golang
req = req.WithContext(context.WithValue(req.Context(), "sessionStore", sessionStore))
```

I would make a PR, except I don't know enough about how to detect the go version to switch it....
